### ISSUE TITLE
UX review

### ISSUE THREAD

**Issue by myninka** [NativeScript/nativescript-sdk-examples-ng#14]
- [x] Loading screen different by default - I will provide the images
- [x] "Examples list" should be renamed to "Examples"
- [x] Avoid using Title Case everywhere in the UI. Use Sentence case instead.
- [x] **All list views** in the app should have the following design:
  - [x] Item height: at least 44 pt. If you have more than 1 row of text it can be more
  - [x] Text alignment: vertically centered, horizontally left aligned.
  - [x] Android left/right padding: 16
  - [x] iOS left/right padding: 15
  - [x] Padding top/bottom: 16
  - [x] Text size: 16
  - [x] Text color: 404040
- [x] Android should have back button in ActionBar
- [x] iOS should remove the back btn label in ActionBar for the main navigation
- [x] iOS examples list: the items are very hard to tap in order to navigate to the example screen. Sometimes I have to tap 3-4 times until navigating.
- [x] Template for **each example**
  - [x] iOS padding: 15 - exceptions for the controls which usually takes the whole available space like: action bar, search bar, tab view, list view, date/time pickers etc.
  - [x] Android padding: 16 - exceptions for the controls which usually takes the whole available space like: action bar, tab bar, list view, segmented bar
  - [x] Text size: 15
  - [x] Buttons should look like buttons - this is especially valid for iOS: you can take a look at these designs here: R:\NativeScript\Design_Theme\Basics.png for the buttons' design
  - [x] Text fields/views should look apart - this is especially valid for iOS: you can take a look at these designs here: R:\NativeScript\Design_Theme\Basics.png for the text fields' design
  - [x] If the example have multiple input controls which require interaction with the user make sure they are positioned with appropriate margins between them. At least 44pt in each direction-  this is mandatory. Take a look at Switch,Text example Also Switchs -> Switches
- [x] **ListView** examples
  - [x] take a look at these designs: R:\NativeScript\Design_Theme\ListView.png. Choose one of the templates and apply it to all examples for the item templates. I suggest the multi line one. 
  - [x] Remove background colors everywhere
  - [x] Do we need item numbers? If we do - choose between ")" and "." stick to it.
  - [x] Customizing example - when you get there, ping me.
- [x] **ListPicker** examples in Android: the text is cut
- [x] **Review the changes and set the next steps**

**Comment by myninka** [comment]
For the new examples:
- [ ] Remove all colors and borders from labels. Each of them.

**Comment by myninka** [comment]
## Android

General UX guidelines [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/wiki/UX-Guidelines)

- [ ] Why the labels and the text in the textfields are the same color? What is offered by the theme?
- [ ] Is this the default text color - where is it defined in the css?
- [ ] Textfields don’t have left and right margins

### Camera
- [ ] back btn is missing

### Content page
- [ ] Both templates have issues. Let’s fix at least the first and remove the second. If the hiding of the app bar is not working let’s do it without it.

### Data entry
- [ ] Alignment - left/right (some elements are clearly not aligned - I suspect the theme)
- [ ] Top/bottom margins between elements (ask Nina)
- [ ] Left/right padding of the screen (globally 15 for iOS, 16 for Android as the rest of the examples)
- [ ] "Forgot password" is a button
- [ ] View password button should not have the border. Also when it is tapped, the cursor should stay on the same place - now it goes at the beginning of the text 
- [ ] Toggle switch is not aligned horizontally with the label and vertically with the rest controls
- [ ] Facebook/Google+ buttons also having issues
- [ ] Typos
Wellcome -> Welcome 
Fogot password -> Forgot password

### Fetch
- [ ] Let the label stays h3, but the text should be regular text with the same size 15

### File system
- [ ] Let’s try different text color for the body text - what are the options in the theme?
- [ ] Let’s change  all headers in the text to h3

### FPS meter
- [ ] No centered text
- [ ] Only h3 and regular text, without h2. h3 text color #111.

### HTTP Module
- [ ] Remove all colors, borders and paddings from the labels. 
- [ ] Apply the same styles as in File system examples

### ListPicker
- [ ] The text is cut in both examples

### ListView 
- [ ] Use item template: looks broken
- [ ] Pressed list item styles are missing
- [ ] Single line items thumbs: the text should not be truncated.
- [ ] Single, Two, Multi line items dividers: they should not be red
- [ ] 2 line items with thumbs: too much space between the title and the text
- [ ] Grouped templates: if there is not a group header style in the theme, ours should be: Roboto Medium 14, #333, with the same bg color of the list view
- [ ] Cards thumbnails: ?
- [ ] Google map header

### Location
- [ ] Textfields
- [ ] Alignment
- [ ] Only h3 and regular text, without h2.  h3 text color #111.

### Modal page
- [ ] Remove all colors, borders and paddings from the labels. 
- [ ] Apply the same styles as in File system examples
- [ ] Alignment
- [ ] Can we use date/time editors? 

### Platform
- [ ] Remove the table borders

### Style
- [ ] Apply style using code example - screen paddings

### Textfield
- [ ] Style - one bottom border
- [ ] Layout: the label should be above the textfields. The textfield should take all the available space of the screen (with paddings).
- [ ] Is there a style “label” - it is slightly different by design
- [ ] Textfield binding: alignment

### Textview
- [ ] Alignment
- [ ] Vertical spacing between element - with the measures of the theme

### Timer module
- [ ] Set timeout example: ?? are those toggle btns? 

### Trace module
- [ ] The size and style of the buttons
- [ ] Remove “Writing a custom trace writer” text

### User feed
- [ ] Is there a way all the content to be scrollable?

**Comment by myninka** [comment]
iOS

General UX guidelines [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/wiki/UX-Guidelines)

- [ ] Why the active color looks so different than Android?
- [ ] Why the labels and the text in the textfields are the same color? What is offered by the theme?
- [ ] Is this the default text color - where is it defined in the css?
- [ ] Textfields should have 4 borders

### Color
- [ ] textfield
- [ ] sliders margin-right

### Content page
- [ ] Both templates have issues. Let’s fix at least the first and remove the second. If the hiding of the app bar is not working let’s do it without it.

### Data entry
- [ ] Top/bottom margins between elements (ask Nina)
- [ ] Forgot password is a button looking
- [ ] View password button pressed state exceeds the borders of the input 
- [ ] Toggle switch not aligned vertically with the rest controls
- [ ] Facebook/Google+ buttons also having issues
- [ ] Typos
Wellcome -> Welcome 
Fogot password -> Forgot password

### Fetch
- [ ] Textfields
- [ ] Let the label stays h3, but the text should be regular text with the same size 15

### File system
- [ ] Textfields
- [ ] Let’s try different text color for the body text - what are the options in the theme?
- [ ] Let’s change  all headers in the text to h3

### FPS meter
- [ ] No centered text
- [ ] Only h3 and regular text, without h2. h3 text color #111.

### HTTP Module
- [ ] Remove all colors, borders and paddings from the labels. 
- [ ] Apply the same styles as in File system examples

### ListView 
Use item template: looks broken
Why the text color of the different examples is different?
Single, Two, Multi line items dividers: they should not be red
2 line items with thumbs: too much space between the title and the text
Grouped templates: if there is not a group header style in the theme, ours should be: SF UI Text Regular 15, #9a9a9a, with the same bg color of the list view
Cards thumbnails: ? without separators

Location
Alignment
Only h3 and regular text, without h2.  h3 text color #111.

Modal page
Remove all colors, borders and paddings from the labels. 
Apply the same styles as in File system examples
Alignment
Do we have date/time editors? If yes we can use them and switch to different layout.

Platform
Remove the table borders

Style
Apply style using code example - screen paddings

Search bar
list view design

Textfield
Layout: the label should be above the textfields. The textfield should take all the available space of the screen (with paddings).
Is there a style “label” - it is slightly different by design
Textfield binding: alignment

Textview
Alignment
Vertical spacing between element - with the measures of the theme

Timer module
Set timeout example: ?? are those toggle btns?
 
Trace module
The size and style of the buttons
Remove “Writing a custom trace writer” text

User feed
Is there a way all the content to be scrollable?
Lets discuss the examples personally

**Comment by myninka** [comment]
## Theme specific

1. Margins/paddings in the list view - still quite large
2. Buttons default margins in Android - I think there is a default margin around the button which is added to ours and the buttons are not aligning well with all the controls
3. Group header style in the list view - do we have one?
4. Pressed list item in list view style for Android is missing, or at least isn’t showing.
5. Style for textfield label - do we have one?
6. Active color iOS/Android - they looks different. I will follow up with a screenshot.
7. Pressed states of the buttons in iOS - still the text color is changing when the button is pressed. Can it stay the same as in normal state?

**Comment by NickIliev** [comment]
CHECK with theme later:

 **DataEntry**
- margins and paddings can not be applied for form >> input-field >. input

**Comment by myninka** [comment]
Please don't forget to remove the margins added to the controls separately, once you set the margin/padding globally for the screen.

**Comment by NickIliev** [comment]
Single line items thumbs: the text should not be truncated. [BUG in Android - ListView is recycling the cells and then the textWrap setting is nor respected]

**Comment by NickIliev** [comment]
Closing this issue as obsolete
